include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    use_setters_to_change_properties: false
    constant_identifier_names: false
    non_constant_identifier_names: false
